/*
 (c) Skimlinks 2009-2019
 Build time: Fri, 23 Aug 2019 08:28:52 GMT
 Version: "3.22.2-stackpath"
*/
(function(){function pd(a){function b(a,b){if(!(!a.parentNode||wb(a)||Q(a,"noskimwords")||Q(a,"noskimlinks")||Q(a,"noskimw")||a.meta&&a.meta.ReadOnly)){var c=xb(a,b)[0];q(c,function(a){!e[a]&&yb(a)&&(e[a]=!0,m.domain_data.domains.push(a))})}}var c=y.get_as_hash_node_dict(),d=Object.keys(c).length;if(d){var e={},f=N(function(a){X(a)}),h=0;q(c,function(c,k){window.setTimeout(function(){try{b(c,k)}catch(qd){f(qd)}finally{h+=1,h===d&&a(Object.keys(e))}},0)})}else a([])}function rd(a){var b=void 0,c=void 0,
d=void 0,e=void 0,f=void 0;c=a;b=e=null;f=5;c.Limit&&(f=c.Limit);d=function(){return c.Priority||0};return{group_id:function(){return e?e.id():0},dec_limit:function(){return f-1},limit:function(){return f},action_type:function(){return c.ActionType},text:function(){return c.OriginalPhrase},start_byte:function(){return c.StartByte},url:function(){return c.Url},multi:function(){return c.Mt?!0:!1},group_priority:function(){return e?e.group_priority():d()},id:function(){return b?b:c.PhraseId},groups:function(){var a;
return(a=c.Groups)?a:[]},title:function(){return c.Unlinked?"":null!=c.ActionTitle?c.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(a){c.Title=c.Unlinked?"":a},occurrence:function(){return c.PhraseOccurrence},set_group:function(a){return e=a},set_id:function(a){return b=a}}}function sd(){var a=u.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-u.loading_started,pref:l.referrer,
uc:ma,t:1,jsf:"",jv:na};Y&&(a.xrf=1);return zb(a)}function Ab(a){q(a,function(a){void 0===m.aff_domains[a]&&(m.aff_domains[a]=null)});return Bb(a,Cb)}function Na(a,b){return 0===b.length?!1:R(a,b.join(","))?!0:a.parentNode?Na(a.parentNode,b):!1}function Db(a,b){var c=a.style.cssText;""!==c&&(c+=" ");var d=g("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==g("link_tooltip",null)&&(a.title=g("link_tooltip"));b&&(Oa&&(d=Oa,-1===d.indexOf("#")&&(d=
"#"+d),c+="color: "+d+" !important; "),Pa&&(c+="font-weight: "+Pa+" !important; "),Z&&(c="double"===Z?c+"border-bottom: 1px double !important; ":"dashed"===Z?c+"border-bottom: 1px dashed !important; ":c+("text-decoration: "+Z+" !important; ")),Qa&&(c+="font-style: "+Qa+" !important; "),g("skimwords_link_style")&&(d=g("skimwords_link_style"),c+=d+"; "),g("skimwords_link_class")&&(a.className=z(a.className+" "+g("skimwords_link_class"))),Ra&&(a.title=Ra),null===a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),
a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"),10)%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function oa(a,b){b=b||pa(a);if(!b)return!0;Eb(b);var c=g("skimlinks_keywee_pixel",null);var d=w(n.location.href,"utm_campaign=fbkw");c&&d&&Sa(c);g("vglnk")&&J(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=n.event,c.cancelBubble=!0));return!0}function Eb(a,b){a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&
(a=Fb(a));if(a){var c=Gb(a);var d=m.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;if(-1!==c.indexOf(d))d=c;else{var e=a,f=J(e,"skimwords-link");if(Q(e,"noskim")||!f&&Q(e,"noskimlinks"))d=c;else{var h=A(e,"data-skim-creative"),p=A(e,"data-skimlinks-tracking")||ma;d=Ta?"&"+Ta:"";var k=F(Ua(),{id:Hb,isjs:1,jv:na,sref:n.location,url:c,xguid:l.cookie,xs:1,xtz:Ib(),xuuid:l.uuid});h&&(k.xcreo=h);l.isAdblockUser&&(k.abp=1);S&&(k.site=S);p&&(k.xcust=p);f&&(k.xs=2,k.xword=A(e,"data-skimwords-word")||
"");if(!e)throw Error("getAnchorMetaData takes an anchor HTML element as an argument");f=C(e,["__skimlinks__"]);f||(f={icust:null,sourceApp:null},qa(e,["__skimlinks__"],f));e=f;e.icust&&(k.xjsf=e.icust);e.sourceApp&&(k.xs=e.sourceApp);d=m.waypointDomain+"/?"+ra(k)+d}}T&&(g("gtag")?td(c):g("ga")?ud(c):g("_gaq")?vd(c):g("pageTracker")&&wd(c));Jb(a,d,b)}return!0}function Kb(a,b){return function(c){c=w(b,c)?c:"en";return xd+"/Incentive_"+a+"_"+c+".js"}}function Lb(a){q(yd,function(b){null!==b.iabVendorId&&
Mb(b.iabVendorId,a)});q(v.partner_consents,function(b,c){var d=sa();var e=C(v,["partner_consents",String(c)]);d=46!==c&&e?e.consent:d;d!==a&&Mb(c,a)});qa(v,["skimlinks_consent"],a)}function Mb(a,b){qa(v,["partner_consents",String(a),"consent"],b)}function sa(){return C(v,["skimlinks_consent"],null)}function Q(a,b,c){for(null==c&&(c=!1);null!=a&&a!==m.html_root;){var d=J(a,b)||J(a,"noskim");if(a.className&&d)return!0;a=c?null:a.parentNode}return!1}function zd(a){var b=void 0;null!==m.exclude_lookup&&
null!==m.include_lookup||Va();if(!a)return!1;var c=m.exclude_lookup;for(b in c)if(Nb.call(c,b)){var d=c[b];if(0===b.indexOf("*")){b=b.substr(1);--d;var e=a.lastIndexOf(b);if(-1!==e&&e===a.length-d)return!0}else if(a===b)return!0}return!1}function Wa(a,b){var c;if(c=g("_merchantSettings"))c=-1!==b.indexOf("itunes.apple.com")||-1!==b.indexOf("itunes.com")||-1!==b.indexOf("phobos.apple.com");return c||zd(b)?!1:Ad(m.hostname,a,void 0)&&Ob(b)}function wb(a){for(var b,c,d,e,f;a&&a!==m.html_root;){d=a.id;
c=0;for(e=aa.length;c<e;c++)if(b=aa[c],J(a,b))return!1;f=m.included_ids;c=0;for(e=f.length;c<e;c++)if(b=f[c],d===b)return!1;e=m.excluded_classes;d=0;for(c=e.length;d<c;d++)if(b=e[d],J(a,b))return!0;a=a.parentNode}return aa.length||m.included_ids.length?!0:!1}function Fb(a){for(;a.parentNode;){a=a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function Bd(){for(var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],b=arguments[1],c=arguments[2],d=0;d<
a.length;d++){var e=Pb(a[d]);if(!U(e))return r(c)?c(e,b):e}return b}function Pb(a,b,c){a=n.skimlinks_settings&&n.skimlinks_settings[a]||n[a];return U(a)?b:r(c)?c(a,b):a}function g(a,b,c){return ta(a)?Bd(a,b,c):Pb(a,b,c)}function Qb(){return C(ua(),["runTimeInfo","isAdblockUser"])}function O(a){return a.replace(/^www\./i,"")}function Rb(){for(var a="",b=0;8>b;b++)a+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);return a}function r(a){return"[object Function]"===Object.prototype.toString.call(a)}
function P(a,b,c){for(var d=0,e=null===a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function va(a){return"console"in window&&r(window.console[a])?window.console[a]:function(){}}function wa(a,b){return P(b,function(b,d){return b&&r(a[d])},!0)}function Cd(){try{var a=JSON.stringify({a:1});return 1===JSON.parse(a).a}catch(b){return!1}}function B(a,b){var c=Error(b);c.name=a;Sb(c,"getPrototypeOf"in Object?Object.getPrototypeOf(this):this.__proto__);Error.captureStackTrace&&Error.captureStackTrace(c,
B);return c}function Sb(a,b){"setPrototypeOf"in Object?Object.setPrototypeOf(a,b):a.__proto__=b}function U(a){return"undefined"===typeof a||null===a}function ta(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function q(a,b){if(ta(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)K(a,c)&&b(a[c],c,a)}function F(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);U(a)&&(a=
{});q(b,function(b){U(b)&&(b={});q(Object.keys(b),function(c){a[c]=b[c]})});return a}function Xa(a,b){var c=[];q(a,function(d,e){b(d,e,a)&&c.push(d)});return c}function Tb(){return Xa(0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],function(a){return!!a})}function Ya(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];q(a,function(d,e){c.push(b(d,e,a))});return c}function z(a){return U(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function G(a){return"boolean"===typeof a}function Dd(){var a=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:"";return 0===(0<arguments.length&&void 0!==arguments[0]?arguments[0]:"").slice(2<arguments.length&&void 0!==arguments[2]?arguments[2]:0).indexOf(a)}function Ub(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"",c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0;c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function Vb(a){return encodeURIComponent(a).replace(/[!'()*~]/g,
function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function xa(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,c=document.createElement("a");c.href=b?a:Ed(a);try{return O(c.hostname)}catch(d){return""}}function Ed(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"http",c="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(c=/^\/\//.test(a)?b+":":b+"://");return""+c+a}function Ad(a,b){var c=xa(b,2<arguments.length&&void 0!==arguments[2]?arguments[2]:!0),
d=Ub(c,"."+a)||Ub(a,"."+c);return c!==a&&!d}function Wb(a){a=a.replace(/^\??/,"").split("&");return P(a,function(a,c){if(!c)return a;var b=c.split(/=/),e=b[0];if(1===b.length)return a[e]=!0,a;a[e]=decodeURIComponent(b.splice(1).join(""));return a},{})}function ya(a){var b=Wb(window.location.search);return K(b,a)}function ra(a,b){var c=[];b=b||Vb;q(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}function Za(a,b,c,d){function e(){if(r(d.onError)){var b=400<=k.status&&500>k.status,c=500<=k.status&&
600>k.status;d.onError(new (0===k.status?Fd:b?Gd:c?Hd:Id)(p+" "+a+" "+k.status))}}b=b||{};d=d||{};var f=d.data,h=d.headers||{},p=d.method||"GET",k=new XMLHttpRequest;d.withCredentials&&(k.withCredentials=!0);b=ra(b);b.length&&(a=a+"?"+b);k.open(p,a);q(h,function(a,b){k.setRequestHeader(b,a)});k.onload=function(){if(r(c))if(200<=k.status&&300>k.status){var a=void 0;try{a=JSON.parse(k.responseText)}catch(ff){a=k.responseText}c(a)}else e()};k.onerror=e;k.send(f);return k}function C(a,b,c){if(!a||!b||
!b.length)return c;for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a&&f in a)a=a[f];else return c}return a}function ua(){return window.__SKIM_JS_GLOBAL__&&r(window.__SKIM_JS_GLOBAL__.getDebugInfo)?window.__SKIM_JS_GLOBAL__.getDebugInfo():{}}function Jd(a){var b=/(?::(\d+))?:(\d+)$/,c=/^([^ ]+)\s\((.*)\)$/,d={filename:a,"function":"?",lineno:null,colno:null,in_app:!0};c.test(a)&&(a=a.match(c).slice(1),a=Xb(a,2),c=a[1],d["function"]=a[0],d.filename=c);b.test(d.filename)&&(a=d.filename.match(b).slice(1),
c=Xb(a,2),a=c[0],c=c[1],a&&c?(d.lineno=parseInt(a,10),d.colno=parseInt(c,10)):!a&&c&&(d.lineno=parseInt(c,10)),d.filename=d.filename.replace(b,""));return d}function Kd(a){a=a.stack.replace(a.toString(),"").replace(/^\s+at\s+/gm,"").split("\n");a=Ya(a,function(a){return z(a)});a=Tb(a);a.reverse();return Ya(a,Jd)}function X(a,b){if(a&&Yb){Zb.push(a);try{Ld.sendError(a,b)}catch(d){if(d===a)$b.error(a);else{var c=new Md;c.__sentryExtraData__={logger_error_message:d.message,logger_error_stack:d.stack,
initial_error_message:a.message,intial_error_stack:a.stack};throw c;}}}}function x(a){return r(a)?function(){try{a.apply(this,arguments)}catch(b){X(b)}}:a}function N(a){var b=!1,c=void 0;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}function Nd(a,b){return P(Object.keys(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function H(a,b){var c=Array.prototype.slice.call(arguments,2),d=x(a);return window.setTimeout.apply(window,[d,b].concat(c))}function Od(a,b){var c=!1,d=
void 0;return function(){if(c)return d;H(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function $a(a,b,c){var d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:!1;if(a&&(a.nodeName||a===n))if(I.addEventListener){var e=x(c.bind(a));a.addEventListener(b,e,d)}else a.attachEvent("on"+b,function(){return 7>l.detect.version&&!n.event?(H(c.bind(a,n.event),100),!0):c.call(a,n.event)})}function ab(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:[],c=arguments[3];if(a){var d=
Od(arguments[2],200);q(b,function(b){try{$a(a,b,d,c)}catch(f){}})}}function pa(a){var b=void 0;a=a.target||a.srcElement||a.originalTarget;var c=null!=a?null!=(b=a.nodeName)?"function"===typeof b.toUpperCase?b.toUpperCase():void 0:void 0:void 0;"A"!==c&&"AREA"!==c&&(a=Fb(a));return a}function A(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}function Pd(a,b){b=b||ac;a.skimlinksOriginalHostname=
a.hostname;a.skimlinksOriginalHref=a.href;H(function(){a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref},b)}function Jb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||Pd(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===l.detect.browser&&d&&(c=a.innerHTML);a.href=b;c&&c!==a.innerHTML&&(a.innerHTML=c)}}function bc(a,b){var c=b?b.charAt(0).toUpperCase()+b.slice(1):"";return a["skimlinksOriginal"+c]||a[b]}function w(a,
b){return r(a.indexOf)?-1<a.indexOf(b):!1}function za(a){return w(a,"go.skimresources.com")||w(a,"go.redirectingat.com")||w(m.waypointDomain,a)}function J(a,b){return a&&a.className&&b?w(z(a.className).split(/\s+/),b):!1}function bb(a){var b;(b=wb(a))||(b=A(a,"rel"),b=!(ba?ba===b:!b||!cb(b)));if(b)return"IGNORE";if(b=cc)null===a.offsetParent?b=!0:(b=n.getComputedStyle,b=r(b)?"hidden"===b(a).visibility:!1);if(b)return"IGNORE";b=z(bc(a,"href"));a=O(bc(a,"hostname"));var c=b?/^https?:\/\//.test(b)||
/^\/\//.test(b):!1;if(c&&Wa(b,a)){if(Y)return"TRACK";if(!0===m.aff_domains[a]||K(db,a))return"AFFILIATE";if(za(a))return"PRE_AFFILIATED";if(b=eb)b=!K(m.aff_domains,a)||U(m.aff_domains[a]);return b?"UNKNOWN":""===l.cookie&&dc?"AFFILIATE":"TRACK"}return"IGNORE"}function Qd(a,b){var c=F({},Rd,b||{}),d=document.createElement("script");d.src=a;d.type="text/javascript";d.async=c.async;d.onload=x(c.onLoad);d.onerror=x(function(){X(new Sd(a));c.onError()});document.head.appendChild(d);return d}function ec(){try{window.top.document;
var a=!0}catch(b){a=!1}return a?window.top:window}function fb(a){return fc()[a]}function Td(a,b,c){gb(a)&&gc[a]===b?c(fb(a)):Qd(b,{onLoad:function(){gb(a)&&(gc[a]=b,c(fb(a)))}})}function gb(a){var b=fc();return K(b,a)}function fc(){ca.__SKIM_JS_GLOBAL__||(ca.__SKIM_JS_GLOBAL__={});ca.__SKIM_JS_GLOBAL__.modules||(ca.__SKIM_JS_GLOBAL__.modules={});return ca.__SKIM_JS_GLOBAL__.modules}function hc(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c]}function qa(a,b,c){if(!a||!b||!b.length)return a;
for(var d=b.length,e=a,f=null,h=0;h<d;h++){var p=b[h];if(h===d-1){try{a[p]=c}catch(k){e[f]={},e[f][p]=c}break}(e=!(p in a))||(e=a[p],f=typeof e,e=!(null!==e&&("object"===f||"function"===f)));e&&(a[p]={});e=a;f=p;a=a[p]}return a}function L(){this.ready=!1;this._pendingCallback=[]}function Ud(a,b){return Xa(a,function(a){return a!==b})}function Vd(a){Aa.get(ic+"/iab",{},function(b){v=b;r(a)&&a(v)},{withCredentials:!0})}function hb(a){var b={};if(v){var c=sa();G(c)&&(b["46"]=c);q(v.partner_consents,
function(a,c){G(a.consent)&&(b[c]=a.consent)})}Aa.post(ic+"/iab",{},function(b){v=b;r(a)&&a(v)},{data:JSON.stringify(b),withCredentials:!0})}function Wd(a,b){return a&&a.length&&b?"undefined"!==typeof hc(a,b):!1}function jc(a){Xd(a)?(Yd(a),a=Zd(a)):a=a[Math.floor(a.length*Math.random())];return a}function Zd(a){var b=Math.random(),c=0;return hc(a,function(a){a=c+a.weight;if(b<a)return!0;c=a;return!1})}function Yd(a){a=a.reduce(function(a,c){var b=parseFloat(c.weight);(isNaN(b)||0>b||1<b)&&kc('"weight" field should be a number between (0, 1].');
return a+b},0);1!==a&&kc("Sum of all the weights should be equal 1 but got "+a+".")}function Xd(a){return Wd(a,function(a){return K(a,"weight")})}function kc(a){throw Error("Error in variants setup. "+a);}function Ba(a,b,c){var d=document.createElement(a);q(b||{},function(a,b){var c=b.split(".");qa(d,c,a)});"STYLE"===d.tagName&&(d.type="text/css");"SCRIPT"===d.tagName&&(d.type="text/javascript");lc(d,[].concat(c||[]));return d}function lc(a,b){q(b,function(b){if(ta(b))lc(a,b);else{var c="string"===
typeof b;"STYLE"===a.tagName&&c&&a.styleSheet?a.styleSheet.cssText+=b:(c&&(b=document.createTextNode(b)),a.appendChild(b))}})}function mc(a){if(window.matchMedia&&r(window.matchMedia))return window.matchMedia(a).matches;nc+=1;var b="matchmedia-test-"+nc;var c=Ba("div",{id:b});a=Ba("div",{},[c,Ba("style",{},"\n@media "+a+" {\n    #"+b+" {\n        width: 1px;\n    }\n}")]);document.body.appendChild(a);b=!1;try{var d="getComputedStyle"in window?window.getComputedStyle(c,null):c.currentStyle;b="1px"===
d.width}catch(e){}a.parentNode.removeChild(a);return b}function oc(a){a=a||document;a=a.body||a.getElementsByTagName("body")[0];if(!a)throw new $d;return a}function Sa(a,b,c){if(!V){V=document.createElement("iframe");oc().appendChild(V);var d=V;d.width=0;d.height=0;d.style.display="none"}var e=V.contentDocument||V.contentWindow.document;d=oc(e);d||(d=document.createElement("body"),e.appendChild(d));e=e.createElement("img");e.src=a;e.width=1;e.height=1;r(b)&&(e.onload=x(b));r(c)&&(e.onerror=x(c));
d.appendChild(e)}function Ua(){var a={};ib&&(a.dnt=ib);pc&&(a.fdnt=1);return a}function Ca(a){try{return a()}catch(b){}}function td(a){var b=g("gtag");Ca(function(){b("event",T,{event_category:"click",event_label:a})})}function ud(a){var b=g("ga");Ca(function(){b("send","event","click",T,a)})}function vd(a){var b=g("_gaq");Ca(function(){b.push(["_trackEvent","click",T,a])})}function wd(a){var b=g("pageTracker");b._trackPageview&&Ca(function(){b._trackPageview("/"+T+"/"+a)})}function qc(a){var b=a.href;
b=l.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+l.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,"");b!==a.href&&Jb(a,b);return b}function Da(a,b,c,d){var e=d||{};d=e.forceBeacon||!1;e=e.callback||function(){};c=F({},c,Ua());d?rc(a,b,c,e):jb(a,b,c,e)}function rc(a,b,c,d){c=Object.assign({},c);c.rnd=Math.random();b&&(c.data=JSON.stringify(b));Sa(kb(a,c),d,d)}function jb(a,b,c,d){b=JSON.stringify(b);Aa.post(kb(a,c),{},d,{headers:{"Content-type":"text/plain"},data:b})}function kb(a,
b){var c=ra(b),d=""+ae+a;return c?d+"?"+c:d}function be(){navigator.sendBeacon&&1>1E4*Math.random()&&rc("/__skimjs_preflight__please_ignore__",void 0,void 0,function(){var a={domain_id:Ea,publisher_id:Fa,page_url:n.location.href,impression_id:l.uuid,jv:na};a:{var b=Object.assign({trackingMethod:"sendBeacon"},a);b=JSON.stringify(b);if(navigator.sendBeacon){var c=kb("/generic_tracking/trackingMethodExperiment",void 0);if(navigator.sendBeacon(c,b)){b=!0;break a}}b=!1}jb("/generic_tracking/trackingMethodExperiment",
Object.assign({trackingMethod:"xhr"},a));b||jb("/generic_tracking/trackingMethodExperiment",Object.assign({trackingMethod:"sendBeaconFailed"},a))})}function ce(){var a=Tb([!!sc&&"mouseup","click"]);ab(I,a,function(a){var b=pa(a),d=0===a.button;if(b&&d){d=bb(b);var e=da.moduleName;if(e=!(tc()&&(d===D.AFFILIATE||d===D.PRE_AFFILIATED)&&gb(e)))ya("skimlinks_force_incentive")||ya("skimlinks_incentive_control_group"),e=!0;e&&uc(a,b,d)}},!0)}function de(){ab(I,["auxclick","contextmenu","touchstart"],function(a){if(a=
pa(a)){var b=bb(a);b===D.AFFILIATE||b===D.UNKNOWN?Eb(a,200):b===D.PRE_AFFILIATED&&qc(a)}},!0)}function uc(a,b,c){c===D.AFFILIATE||c===D.UNKNOWN?(vc(b),ea&&A(b,"target",ea),c=(c=A(b,"onclick"))&&w(c.toString(),"return false")?!0:(c=b.onclick)&&r(c)&&w(c.toString(),".preventDefault()")?!0:!1,c?(oa(a,b),(ea?n.open(b.href,ea):n.open(b.href,"_blank")).focus()):oa(a,b)):c===D.PRE_AFFILIATED?qc(b):c===D.TRACK&&(a={publisher_id:Fa,publisher_domain_id:Ea,referrer:n.location.toString(),pref:l.referrer,site:""+
S,url:b.href,custom:A(b,"data-skimlinks-tracking")||ma||"",xtz:l.timezone,uuid:l.uuid,product:"1"},Y&&(a.xrf=1),Da("/naclicks",a,null,{forceBeacon:!0}))}function wc(a){return P(a,function(a,c){return a.concat(c)},[])}function Ga(a){a=a?"."+a:"";return wc(I.querySelectorAll("a[href]"+a+", area[href]"+a))}function ee(a){var b=A(a,"rel"),c=O(a.hostname);!b&&c&&!0===m.aff_domains[c]&&A(a,"rel","nofollow")}function fe(){xc&&q(Ga(),ee)}function ge(){ce();de()}function he(){l.skimlinksEnabled&&(t.on("skim_js_start",
ge),t.on("EVENTS__BEACON_CALLBACK",fe))}function yc(a){var b;return a&&-1!==a.indexOf("class=")&&(b=a.match(/([^[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a}function ie(a,b){a&&b&&q(a,function(a){var c=w(b,a)&&!za(a);m.aff_domains[a]=c})}function lb(a,b){var c=!!a;--E.pendingRequests;a&&(m.beacon.push(a),zc+=1);var d=a=a||{},e=l.cookie,f={};d.consent&&(f.consent=d.consent);d.country&&(f.country=d.country.toUpperCase());d.guid&&""===e&&(f.cookie=d.guid);!G(l.consent)&&"consent"in d&&(f.consent=
d.consent);F(l,f);d=a;ie(d.requestedDomains,d.merchant_domains);d=E.readyStates.beaconApiResponse;c&&!d.ready&&E.readyStates.beaconApiResponse.setReady();"BEACON_CALLBACK__POST_PAGE_LOAD"===b&&E.readyStates.postPageLoadBeaconHandler.setReady();t.publish("EVENTS__BEACON_CALLBACK",{type:b,data:a,isFirstCall:1===zc})}function Bb(a,b){var c=!a||!a.length;if(E.called&&c)E.pendingRequests+=1,b();else{var d=JSON.stringify({pubcode:Hb,page:n.location.href,domains:a});c=Ua();"production"!==je&&(c._=b===Ac?
mb.PRE_PAGE_LOAD:b===Bc?mb.POST_PAGE_LOAD:b===Cb?mb.AUX:"UNKNOWN_BEACON_CALLBACK");E.called=!0;E.pendingRequests+=1;d={headers:{"Content-type":"application/x-www-form-urlencoded"},data:ra({data:d}),withCredentials:!0};Aa.post(""+ke,c,function(c){c.requestedDomains=a;b(c)},d)}}function zb(a){return F({pag:n.location.href,guid:l.cookie,uuid:l.uuid,tz:l.timezone,publisher_id:Fa,publisher_domain_id:Ea},a)}function Cc(a){if(0!==u.awaitedModules.length&&(u.awaitedModules=Xa(u.awaitedModules,function(b){return b!==
a}),0===u.awaitedModules.length)){var b=sd();Da("/page",b)}}function le(a){a=a.match.phrase;return{w:a.text(),lp:a.url(),t:Ha.creative}}function nb(a){a=a||[];var b=P(a,function(a,b,e){a[e]=b;return a},{});u.linksImpressions.unlinked={count:a.length,urls:b};Cc("unlinked")}function ob(a){return String(a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function me(){n.__SKIM_JS_GLOBAL__.bundledEntries.unlinked=!0;if(l.unlinkedEnabled){if(l.skimwordsEnabled)t.on("instant_api_callback_settings",
ne);else t.on("EVENTS__BEACON_CALLBACK",Dc,{type:"BEACON_CALLBACK__POST_PAGE_LOAD"});t.on("dom_changed",Ec);t.on("EVENTS__BEACON_CALLBACK",oe,{type:"BEACON_CALLBACK__AUX"})}}function ne(){var a=fa.settings;2===a.nc?l.unlinkedEnabled&&Ab(m.domain_data.domains):l.unlinkedEnabled&&(a.includes?(M&&M.length&&(a.excludes=a.excludes.concat(M)),y.traverse(a.includes,a.excludes,a.read_onlys)):M&&M.length?y.traverse(["body"],M,[]):y.traverse(["body"],[],[]));Dc()}function Dc(){a:{var a=I.getElementsByTagName("body");
if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi.exec(a),b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(l.skimwordsEnabled||y.traverse([],M,[]),Ec()):nb()}function Ec(){pd(function(a){a.length?Ab(a):nb()})}function oe(){var a=[];Object.keys(m.aff_domains).length&&(q(Ha.url_spans,function(b){m.aff_domains[b.match.domain]&&(Fc(b.node,b.match,!0),a.push(le(b)))}),H(function(){var a;var c=Ga("skimlinks-unlinked");
var d=[];var e=0;for(a=c.length;e<a;e++){var f=c[e];d.push(Gc(f))}return d},10));nb(a)}function pb(a,b,c,d,e){d=((d||0)/1E3).toFixed(2);b={consent:a,publisher_domain_id:Ea,publisher_id:Fa,decision_time:parseFloat(d),test_case:da.id,page_url:b,destination_url:c};Hc.setItem("skimCONSENT",a);Da("/consent",b,null,{callback:e})}function pe(a){(a=C(a,["data","country"]))&&w(qe,a.toUpperCase())?Vd(re):(Ic.setReady(),t.publish("EVENTS__CONSENT_RESOLVED"))}function re(){var a=l.consent,b=l.pageLocation,c=
sa();G(a)&&null===c?(Lb(a),hb()):G(c)&&c!==a&&pb(c,b,"IAB_CONSENT_SYNC",0);Ic.setReady();t.publish("EVENTS__CONSENT_RESOLVED")}function se(a){var b=z(a.skimlinksOriginalHref||a.href);return Ba("a",{href:b,target:"_blank"===a.target?"_blank":"_top",rel:a.rel})}function Jc(a,b){var c=fb(da.moduleName);if(c){var d=se(a);d.onclick=function(a){l.skimlinksEnabled&&uc(a,d,b)};var e=z(a.skimlinksOriginalHref||a.href),f="_blank"===a.target,h=l.pageLocation,p=Date.now(),k=N(function(a){var b=Date.now()-p;Lb(a);
if(f)pb(a,h,e,b),hb(),d.click();else{var c=N(function(){d.click()}),k=0,g=function(){k+=1;2===k&&c()};pb(a,h,e,b,g);hb(g);H(c,1E3)}});new c({anchorClone:d,publisherDomain:O(m.hostname),merchantDomain:xa(e),onResolve:function(){return k(!0)},onReject:function(){return k(!1)}})}}function te(){if(tc()){var a=da.moduleName,b=da.getUrl;var c=ya("skimlinks_locale");var d=Wb(window.location.search).skimlinks_locale;c=c?d:(c=C(v,["country"],l.country))?ue[c.toUpperCase()]||"en":"en";c=C(v,["locale"],c);b=
b(c);Td(a,b,ve)}}function ve(){ab(I,["click"],function(a){var b=pa(a),c=0===a.button;b&&c&&(c=bb(b),c===D.AFFILIATE||c===D.PRE_AFFILIATED)&&(a&&(a.preventDefault&&r(a.preventDefault)?a.preventDefault():a.returnValue=!1),Jc(b,c))},!0)}function we(){t.on("skim_js_init",function(){n.__SKIM_JS_GLOBAL__.bundledEntries.GDPRConsent=!0;n.skimlinksAPI.consent={openConsentModal:Jc}});t.on("EVENTS__CONSENT_RESOLVED",te)}function xe(){if(Object.keys(u.linksImpressions.skimlinks.urls).length){var a=zb({dl:u.linksImpressions.skimlinks.urls,
hae:u.linksImpressions.skimlinks.count?1:0,typ:"l"});Da("/link",a)}}function ye(){return P(Ga(),function(a,b){var c=z(b.href),d=O(b.hostname),e;if(!(e=!(!J(b,"skimwords-link")&&!J(b,"skimlinks-unlinked"))||!Wa(c,d)))if(b)if(e=Kc.join(", ")){b:{var f=b;if(r(window.Element.prototype.closest))e=f.closest(e);else{for(;f&&1===f.nodeType;){var h=f;var p=e,k=window.Element.prototype;k=k.matches||k.msMatchesSelector||k.mozMatchesSelector||k.webkitMatchesSelector;if(r(k))h=k.call(h,p);else{p=(h.document||
h.ownerDocument).querySelectorAll(p);for(k=0;p[k]&&p[k]!==h;)k+=1;h=!!p[k]}if(h){e=f;break b}f=f.parentNode}e=null}}e=!!e}else e=!1;else e=!1;if(e)return a;(e=a.urls[c])||(e={count:0,ae:!0===m.aff_domains[d]||(null===m.aff_domains[d]||void 0===m.aff_domains[d])&&eb&&!za(d)?1:0});e.count++;a:{if(-1!==c.indexOf("#slm-")&&(d=c.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1],10)===10*d[1])){d=parseInt(d[1],10);break a}d=null}d&&(e.slmcid=d);d=e;1===d.ae&&a.count++;d.slmcid&&(e=d.slmcid,w(u.campaign_ids,
e)||u.campaign_ids.push(e));if(!Lc&&0===d.ae)return a;a.urls[c]=d;return a},{urls:{},count:0})}function Mc(a){a=a||0;Nc&&(0!==E.pendingRequests&&5>a?H(function(){Mc(a+1)},400*a):(u.linksImpressions.skimlinks=ye(),Cc("main-tracking"),xe()))}function ze(){Mc(0)}function Ae(){u.awaitedModules.push("main-tracking");l.skimwordsEnabled&&u.awaitedModules.push("skimwords");l.unlinkedEnabled&&u.awaitedModules.push("unlinked");t.on("EVENTS__BEACON_CALLBACK",ze,{type:"BEACON_CALLBACK__POST_PAGE_LOAD"});be()}
function Be(){}function Oc(a,b){W||1E3<b?r(a)&&(W?qb?a(!0):a(!1):a(!1)):H(Oc,b*=2,a,b)}function Pc(){W||(ha.complete&&ia.complete&&(W=!0),W&&"0"!=ha.width&&"0"==ia.width&&(qb=!0))}function Ce(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=Ya(Qc,b);return w(c,b(a))}function De(){return{skimOptions:Ee,runTimeInfo:F({},{aff_domains:m.aff_domains},{consentState:v},{loggedErrors:Zb},l)}}function Rc(a){var b;var c=Ga();var d=[];var e=0;for(b=c.length;e<b;e++){var f=c[e];
var h=O(f.hostname);var p=z(f.href);f=A(f,"rel");!h||!Wa(p,h)||(ba?ba!==f:f&&cb(f))||za(h)||void 0!==m.aff_domains[h]||(d.push(h),m.domain_data.domains.push(h),m.aff_domains[h]=null)}Bb(d,a)}function Fe(){n.__SKIM_JS_GLOBAL__||(n.__SKIM_JS_GLOBAL__={});if(!n.__SKIM_JS_GLOBAL__.init){n.skimlinksAPI={};n.__SKIM_JS_GLOBAL__.init=!0;n.__SKIM_JS_GLOBAL__.getDebugInfo=De;n.__SKIM_JS_GLOBAL__.bundledEntries=Ge;if(Ce(m.hostname)||rb&&I.querySelector(rb))l.skimlinksEnabled=!1,l.skimwordsEnabled=!1,l.unlinkedEnabled=
!1;"msie"===l.detect.browser&&8>=l.detect.version&&(l.skimwordsEnabled=!1);He.detect(function(a){l.isAdblockUser=a});t.publish("skim_js_init");w(["interactive","complete"],I.readyState)?H(ja,0):(Rc(Ac),document.addEventListener("DOMContentLoaded",ja),document.addEventListener("load",ja));t.publish("skim_js_start")}}var $b={log:va("log"),info:va("info"),warn:va("warn"),error:va("error")},Yb=function(){var a=!0;try{var b=[Cd(),!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest),wa(document,
["querySelector","querySelectorAll"]),wa(Object,["keys"]),wa([],["indexOf"]),wa("",["indexOf"])];a=P(b,function(a,b){return a&&b},!0)}catch(c){a=!1}!1===a&&$b.info("[Skimlinks] Your browser doesn't support the base features necessary to run our javascript.");return a}();B.prototype=Object.create(Error.prototype,{constructor:{value:Error,enumerable:!1,writable:!0,configurable:!0}});Sb(B,Error);var $d=B.bind(null,"DocumentBodyNotFound"),Ie=B.bind(null,"PixelDropFailed"),Sd=B.bind(null,"ScriptDropFailed"),
Id=B.bind(null,"XhrError"),Gd=B.bind(null,"XhrError4xx"),Hd=B.bind(null,"XhrError5xx"),Fd=B.bind(null,"XhrErrorZero"),Md=B.bind(null,"SentryLoggerError");B.bind(null,"SendBeaconFailedError");var na="3.22.2-stackpath",Je="https://s.skimresources.com/js/GDPR",xd="https://s.skimresources.com/js/incentive",Ke="*.criteo.com *.g.doubleclick.net *mjxads.internet.com *overture.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *youtube.com m.skimresources.com paid.outbrain.com track.celtra.com traffic.outbrain.com trc.taboola.com zergnet.com ad.doubleclick.net".split(" "),
Le=["noskim","norewrite"],ke="//r.skimresources.com/api/",db={"t.umblr.com":{name:"z"}},Hb="725X1342",Fa=725,Ea=1342,ae="//t.skimresources.com/api/v2",ic="//api.skimlinks.mgr.consensu.org",Me="https://sl-sentry.skimlinks.com",Sc="f648b8dfc7284fad8af093653eafd6ca",je="production",mb={PRE_PAGE_LOAD:"PRE_PAGE_LOAD",POST_PAGE_LOAD:"POST_PAGE_LOAD",AUX:"AUX"},Xb=function(){return function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in
Object(a)){var c=[],d=!0,e=!1,f=void 0;try{for(var h=a[Symbol.iterator](),p;!(d=(p=h.next()).done)&&(c.push(p.value),!b||c.length!==b);d=!0);}catch(k){e=!0,f=k}finally{try{if(!d&&h["return"])h["return"]()}finally{if(e)throw f;}}return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),Ne=1>1E3*Math.random(),Ld={sendError:function(a,b){if(!Sc)throw a;var c=b;c=(c=G(c)?c:!1)||Ne?a instanceof Ie&&Qb()?!1:!0:!1;if(c){c=Me+"/api/46/store/";var d={sentry_version:"7",sentry_client:"raven-js/3.26.4",
sentry_key:Sc};var e={country:C(ua(),["runTimeInfo","country"]),beacon_consent:C(ua(),["runTimeInfo","consent"]),iab_consent:C(ua(),["runTimeInfo","consentState","skimlinks_consent"]),is_adblock_user:Qb(),is_top_frame:window.top===window};e={event_id:Rb(),project:"46",platform:"javascript",logger:"javascript",release:na,exception:{values:[{type:a.name,value:a.message,stacktrace:{frames:Kd(a)}}]},request:{headers:{"User-Agent":navigator.userAgent},url:location.href},extra:F({original_stacktrace:a.stack},
a.__sentryExtraData__,e)};Za(c,d,null,{method:"POST",data:JSON.stringify(e)})}}},Zb=[],Ib=N(function(){return(new Date).getTimezoneOffset()}),Tc=window.skimlinks_context_window||null,n=Tc?window[Tc]:window,I=n.document,Hc={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},sb=g("noskim",!1),Oe=g("noskimlinks",!1),Pe=g("noskimwords",!0),Qe=g("nounlinked",
!1),Re=g("skimwords_standard",false),Se=g("skimwords_lite",false),Te=g("skimwords_diy",false),Ue=g("skimwords_diy_filter",false),Uc=!sb&&!Oe,Vc=!sb&&!Pe,Wc=!sb&&!Qe,ib=g("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==a?1:0}),pc=g("skimlinks_nocookie",!1),aa=g("skimlinks_included_classes",[]),Xc=g("skimlinks_excluded_classes",[]),
Yc=g("skimlinks_exclude",[]),Zc=g("skimlinks_include",[]),$c=g("skimlinks_included_ids",[]),tb=g("skimlinks_exrel",""),ba=g("skimlinks_byrel",!1),cc=g("skimlinks_ignore_hidden_links",false),Kc=g("skimlinks_link_impression_exclude_selector",[]),xc=g("skimlinks_add_nofollow",
false),sc=g("skimlinks_before_click_handler",false,function(a,b){return G(a)?a:b}),dc=g("skimlinks_first_party_na",!1),Ve=g("skimlinks_cookie_sync_optout",!0),Nc=!g("noimpressions",!1),Lc=false,ac=g("skimlinks_replace_timeout",300,function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),eb=g("skimlinks_affiliate_unknown_links",true),
ea=g("skimlinks_target",null),We=g("skimlinks_ajax_rerun",false),M=[],Y=g("skimlinks_revenue_forecast",false),ad=g("skimlinks_noright",false),bd=g("skimlinks_url_extraction_rules",!1)||false,Ta=g("skimlinks_extra_redir_params",[]).join("&"),ma=g(["affiliate_tracking","skimlinks_tracking"],!1),Ia=g("force_location"),S=g(["skimlinks_site",
"skimlinks_sitename"],!1),ub=g("skimlinks_domain","wordpress.redirectingat.com"),T=g("skimlinks_google",false,function(a,b){return a?G(a)?a?"skimout":"":z(a):b?"skimout":""}),Qc=g("noskim_domains",[]),Xe=g("skimwords_horizontal_distance",80),Ye=g("skimwords_vertical_distance",80),Ze=false,Oa=g("skimwords_color",null),Pa=g("skimwords_weight",
null),Z=g("skimwords_decoration",null),Qa=g("skimwords_style",null),Ra=g("skimwords_title",null),rb=g("no_skim_selector",""),cd=g("skimlinks_force_consent",!1),Ee={SW_STANDARD:Re,SW_LITE:Se,SW_DIY:Te,SW_DIY_FILTER:Ue,HAS_SKIMLINKS:Uc,HAS_SKIMWORDS:Vc,HAS_UNLINKED:Wc,DO_NOT_TRACK:ib,NO_COOKIE:pc,SL_INCLUDED_CLASSES:aa,SL_EXCLUDED_CLASSES:Xc,SL_EXCLUDED_DOMAINS:Yc,
SL_INCLUDED_DOMAINS:Zc,SL_INCLUDED_IDS:$c,SL_EXCLUDED_REL:tb,SL_INCLUDED_REL:ba,SL_IGNORE_HIDDEN_LINKS:cc,SL_IMPRESSION_EXCLUDED_SELECTORS:Kc,SL_ADD_NOFOLLOW:xc,SL_BEFORE_CLICK_HANDLER:sc,SL_FIRST_PARTY_NA:dc,SL_COOKIE_SYNC_OPTOUT:Ve,SL_TRACK_IMPRESSION:Nc,WITH_NA_LINK_IMPRESSIONS:Lc,SL_REPLACE_TIMEOUT:ac,SL_AFFILIATE_UNKNOWN_LINKS:eb,SL_TARGET:ea,AJAX_SUPPORT:We,UNLINKED_EXCLUDES:M,SL_FORECAST:Y,NO_RIGHT_CLICK:ad,USE_MERCHANT_URL_EXTRACTION_RULES:bd,EXTRA_REDIR_PARAMS:Ta,CUSTOM_TRACKING_VAR:ma,FORCE_LOCATION:Ia,
SITE_NAME:S,CUSTOM_WAYPOINT_DOMAIN:ub,GOOGLE_TRACKING_ACTION_NAME:T,NO_SKIM_DOMAINS:Qc,SW_HORIZONTAL_DISTANCE:Xe,SW_VERTICAL_DISTANCE:Ye,SL_PROFILING:!1,TRACK_COOKIE_SYNCS:Ze,SW_LINK_COLOR:Oa,SW_LINK_WEIGHT:Pa,SW_LINK_DECORATION:Z,SW_LINK_STYLE:Qa,SW_LINK_TITLE:Ra,NO_SKIM_SELECTOR:rb,SL_CONSENT:"ae",FORCE_CONSENT:cd,M101_TRACKING_ID:null,M101_CUSTOM_DOM_DETECTION:false},l=function(){var a=I.referrer||document.referrer||"",b=Ia||n.location.href;
var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var f=b.split("?");if(2<=f.length){b=f.shift();f=f.join("?");e=encodeURIComponent(e)+"=";f=f.split(/[&;]/gi);for(var h=f.length-1;0<=h;h--)Dd(f[h],e)&&f.splice(h,1);b=b+"?"+f.join("&")}}"?"===b[b.length-1]&&
(b=b.substr(0,b.length-1));c=b;d=Hc.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];b={browser:b[1]||"",version:parseFloat(b[2])||0};return{cookie:"",country:"",locale:"",consent:d,detect:b,isAdblockUser:!1,pageLocation:c,referrer:a,timezone:Ib(),uuid:Rb(),skimwordsEnabled:Vc,skimlinksEnabled:Uc,unlinkedEnabled:Wc}}(),
m=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=Ia?xa(Ia,!1):n.location.hostname;return{aff_domains:{},beacon:[],domain_data:{domains:[]},exclude:Yc,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(Xc),has_been_called:!1,hostname:b,html_root:a,include:Zc,include_lookup:null,included_classes:aa,included_ids:$c,links:[],links_tracked:!1,target:null,waypointDomain:ub?"http://"+ub:"//go.skimresources.com"}}(),fa={branded_merchant:!1,
branded_merchant_url:!1,data:void 0,debug:0,force_country:!1,force_domain_check:!1,force_tree:!1,handler_attached_hook:!1,handlers:0,hover_name:"dark",link_all:!1,lite:!1,maxproducts:3,merchant_excludes:!1,merchant_includes:!1,no_limit:!1,noVisual:!1,original_request:void 0,prio_threshold:0,request_counter:0,settings:null,send_in_progress:!1,x_min_visual_distance:80,y_min_visual_distance:80},Ha={creative:"500005",url_spans:[]},t={topics:{},on:function(a,b,c){ta(this.topics[a])||(this.topics[a]=[]);
var d=void 0;c&&(d=function(a){Nd(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){q(this.topics[a]||[],function(a){r(a)&&a(b)})}},Va=void 0,cb=void 0,Ob=void 0,Nb={}.hasOwnProperty,$e=[].indexOf;Va=function(){var a;m.exclude_lookup={};m.include_lookup={};S&&m.exclude.push(S);var b=m.exclude.concat(Ke);var c=0;for(a=b.length;c<a;c++){var d=b[c];m.exclude_lookup[d]=d.length}b=m.include;c=0;for(a=b.length;c<a;c++)d=b[c],m.include_lookup[d]=d.length;return m.exclude_lookup};Ob=function(a){var b=
void 0;null!==m.exclude_lookup&&null!==m.include_lookup||Va();if(!a)return!1;if(0===m.include.length)return!0;var c=m.include_lookup;for(b in c)if(Nb.call(c,b)){var d="*"===b.substr(0,1);var e="*"===b.substr(b.length-1,1);b=b.replace(/\*/g,"");if(d&&e){if(-1!==a.indexOf(b))return!0}else if(d){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(e){if(0===a.indexOf(b))return!0}else if(a===b)return!0}return!1};cb=function(a){var b;if(!a)return!1;var c=a.toLowerCase().split(/\s+/);
a=tb?[tb.toLowerCase()]:[];a=a.concat(Le);var d=0;for(b=c.length;d<b;d++){var e=c[d];if(0<=$e.call(a,e))return!0}return!1};var D={AFFILIATE:"AFFILIATE",PRE_AFFILIATED:"PRE_AFFILIATED",UNKNOWN:"UNKNOWN",TRACK:"TRACK",IGNORE:"IGNORE"},Rd={async:!0,onError:function(){},onLoad:function(){}},ca=ec(),gc={},ue={AT:"de",BE:"fr",BG:"bg",CY:"el",CZ:"cs",DE:"de",DK:"da",EE:"et",ES:"es",FI:"fi",FR:"fr",GB:"en",GR:"el",HR:"hr",HU:"hu",IE:"en",IT:"it",LT:"lt",LU:"fr",LV:"lv",MT:"en",NL:"en",PL:"pl",PT:"pt",RO:"ro",
SE:"sv",SI:"sl",SK:"sk"},qe="AT BE BG CY CZ DE DK EE ES FI FR GB GR HR HU IE IT LT LU LV MT NL PL PT RO SE SI SK".split(" "),Aa={get:function(a,b,c,d){d=F({onError:X},d,{method:"GET"});Za(a,b,x(c),d)},post:function(a,b,c,d){d=F({onError:X},d,{method:"POST"});Za(a,b,x(c),d)}};L.prototype.whenReady=function(a){this.ready?a():this._pendingCallback.push(a)};L.prototype.setReady=function(){this.ready||(this.ready=!0,this._callPendingCallbacks())};L.prototype._callPendingCallbacks=function(){this._pendingCallback.forEach(function(a){setTimeout(a,
0)});this._pendingCallback=[]};var yd=[{label:"lotame",url:"//sync.crwdcntrl.net/map/c=7505/tp=SKIM/?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[2,"days"],priority:1,iabVendorId:95,active:!0},{label:"blue_kai",url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",resyncAfter:[1,"days"],priority:2,iabVendorId:null,
active:!0},{label:"dfp",url:"//cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[1,"days"],priority:2,iabVendorId:null,active:!0},{label:"mediamath",url:"//pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",resyncAfter:[1,"days"],priority:2,iabVendorId:79,active:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",
resyncAfter:[1,"days"],priority:2,iabVendorId:32,active:!0},{label:"eyeota",url:"//ps.eyeota.net/match?bid=dn9h51u&r=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Deyeota%26provider_id%3D%7BUUID_dn9h51u%7D%26skim_mapping%3Dtrue",resyncAfter:[1,"days"],priority:2,iabVendorId:120,active:!0},{label:"exelate",url:"//x.skimresources.com/?provider=exelate",resyncAfter:[1,"days"],priority:1,iabVendorId:373,active:!0},{label:"avocet",url:"https://ads.avocet.io/getuid?url=https%3A%2F%2Fx.skimresources.com%2F%3Fskim_mapping%3Dtrue%26provider%3Davocet%26provider_id%3D%7B%7BUUID%7D%7D",
resyncAfter:[1,"days"],priority:3,iabVendorId:63,active:!0},{label:"tapad",url:"//x.skimresources.com/?provider=tapad",resyncAfter:[3,"days"],priority:3,iabVendorId:89,active:!0},{label:"trade_desk",url:"//match.adsrvr.org/track/cmf/generic?ttd_pid=qakudad&ttd_tpi=1",resyncAfter:[3,"days"],priority:3,iabVendorId:21,active:!0},{label:"adobe",url:"//x.skimresources.com/?provider=adobe",resyncAfter:[2,"days"],priority:2,iabVendorId:264,active:!0},{label:"zeotap_dbm",url:"//x.skimresources.com/?provider=zeotap_dbm",
resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0},{label:"zeotap_us_latam",url:"//x.skimresources.com/?provider=zeotap_us_latam",resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0,includedCountries:"US MX BR PE CL AR CO".split(" ")}],Ic=new L,v={},af="AT BE BG CY DE ES FR GB GR IE IT LU MT NL PL PT SK".split(" "),tc=N(function(){var a=ec();if(r(a.__cmp)||"msie"===l.detect.browser&&8>=l.detect.version)return!1;if(cd||ya("skimlinks_force_consent"))return!0;var b=sa();a=C(v,["country"],
l.country);b=G(b);a=!!a&&w(af,a.toUpperCase());return!b&&a});B.bind(null,"InvalidVariantConfig");var bf=[{id:1,moduleName:"ConsentA",getUrl:function(a,b){return function(c){c=w(b,c)?c:"en";return Je+"/Consent_"+a+"_"+c+".js"}}("A",["bg","de","el","en","es","fr","it","pl","pt","sk"])}],da=jc(bf),nc=0;N(function(){return mc("screen and (max-device-width: 767px)")});N(function(){return mc("(orientation: landscape)")});var cf=[{id:1,moduleName:"IncentiveA",getUrl:Kb("A",["en"]),weight:.75},
{id:2,moduleName:"IncentiveB",getUrl:Kb("B",["en"]),weight:.25}];jc(cf);var V=void 0,Gb=void 0;Gb=function(a){var b=void 0;if(bd){var c=O(a.hostname);if(c in db)return c="[&?]"+db[c].name+"=(http[^&]+)",c=new RegExp(c),decodeURIComponent(null!=(b=a.href)?b.match(c).pop():void 0)||a.href}return a.href};var vc=void 0;vc=function(a){var b,c=void 0;var d=g("skimlinks_strip_attribute",!1);if(!d)return!1;for(c in d)if(K(d,c)){var e=d[c];(b=A(a,c))&&0===b.indexOf(e)&&(b=b.substr(e.length),
A(a,c,b))}return!0};var Fc=void 0,dd=void 0,ed=void 0,vb=void 0,fd=void 0,gd=void 0,hd=void 0,id=void 0,Ja=void 0,R=void 0,jd=void 0,ka=void 0,Ka=void 0,La=void 0,Ma=void 0,kd=void 0,la=void 0,ld={}.hasOwnProperty;Ka=0;La=null;Ma=0;la=!1;ka={};gd=function(a){ka[a]=ka[a]||0;ka[a]++;return a+"_"+ka[a]};ed=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?
(a=a.split("[class^="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};R=function(a,b){var c;var d=b.split(",");var e=0;for(c=d.length;e<c;e++){b=d[e];b=z(b);b=ed(b);var f=!0;var h=(h="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var p=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===
b.tag||(f=!1);b["class"]&&(!h||h!==b["class"]&&0!==h.indexOf(b["class"]))&&(f=!1);b.id&&(!p||p!==b.id&&-1===p.indexOf(b.id))&&(f=!1);if(f)return!0}return!1};vb=function(a,b){return R(a,b)?[a]:wc(a.querySelectorAll(b))};hd=function(a,b){return 0<a.querySelectorAll(b).length};Ja=function(a,b){return 0===b.length||R(a,b.join(","))?!0:a.parentNode?Ja(a.parentNode,b):!1};id=function(a){var b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===b&&250===a||250===
b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};fd=function(){var a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==n.location.href.indexOf(".google.")?(a.push("td.gac_c"),
a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==n.location.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==n.location.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==n.location.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),
a.push("div.sb_adsNv2"),a.push("div[class*=sb_ads]"));return a};jd=function(a){var b;var c={};var d=0;for(b=a.length;d<b;d++){var e=a[d];c[e]=!0}return c};dd=function(){Ka=0;t.publish("dom_changed")};kd=function(a,b,c,d){var e=void 0,f=void 0,h=void 0,p=void 0,k=void 0,g=f=void 0,l=void 0,m=h=void 0,n=h=f=void 0;if((f=a.className||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"")&&("skimlinks-unlinked"===f||"skimwords-link"===f))return!1;if(0===c.length&&0===b.length)return y.traverse_node(a,
!1,"","",d);if(0!==c.length){if(!Na(a,c)){h=y.get_exclude_selector(c);f=y.get_exclude_selector([]);k=h.selector;p=h.needed;e=f.selector;if(0===b.length||Ja(a,b))return y.traverse_node(a,p,e,k,d);h=[];c=0;for(m=b.length;c<m;c++)f=b[c],l=vb(a,f),l.length?h.push(function(){var a;var b=[];var c=0;for(a=l.length;c<a;c++)g=l[c],b.push(y.traverse_node(g,p,e,k,d));return b}()):h.push(void 0);return h}}else if(0!==b.length){if(Ja(a,b))return y.traverse_node(a,!1,"","",d);n=[];h=0;for(m=b.length;h<m;h++)f=
b[h],l=vb(a,f),l.length?n.push(function(){var a;var b=[];var c=0;for(a=l.length;c<a;c++)g=l[c],b.push(y.traverse_node(g,!1,"","",d));return b}()):n.push(void 0);return n}};x(function(a){var b=void 0,c=void 0,d=void 0,e=void 0;e=a.relatedNode||!1;if(!e||fa.send_in_progress||g("stop_skimwords_ajax"))return!1;La&&clearTimeout(La);Ka++;1===Ka&&y.reset();b=fa.settings.excludes||[];c=fa.settings.includes||[];d=fa.settings.read_onlys||[];kd(e,c,b,d);if(y.get_non_colliding_nodes()&&1<=Ma)return La=H(function(){dd()},
1E3)});var y=function(){var a=void 0;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f;if(la)return a;la=!0;var h=this.get_exclude_selector(c);var p=this.get_exclude_selector([]);c=h.selector;h=h.needed;p=p.selector;0===b.length&&b.push("body");b=b.concat(d);for(var g=0,l=b.length;g<l;g++){var m=b[g];m=yc(m);m=document.querySelectorAll(m);var n=e=0;for(f=m.length;e<f;n=++e)n=m[n],this.traverse_node(n,
h,p,c,d)}return a},traverse_node:function(b,c,d,e,f){var h=[];var g=0;for(h.push({node:b,tagName:"",readOnly:!1,parent_id:null});g<h.length;)!(b=h[g].node)||id(b)||Q(b,"noskimwords",!0)||c&&""!==d&&R(b,d)||(h[g].readOnly=!1,b.nodeName&&"#text"!==b.nodeName?(h[g].tagName=b.nodeName,null!==h[g].parent_id&&(h[g].readOnly=h[h[g].parent_id].readOnly),h[g].readOnly||(c&&R(b,e)?h[g].readOnly=!0:w(f,b.nodeName.toLowerCase())&&(h[g].readOnly=!0)),w(f,b.nodeName.toLowerCase())&&(h[g].readOnly=!0)):null!==h[g].parent_id&&
(h[g].tagName=h[h[g].parent_id].tagName,h[g].readOnly=h[h[g].parent_id].readOnly),"msie"===l.detect.browser&&9>l.detect.version&&h[g].readOnly||(b.hasChildNodes()?h=this.add_child_nodes(h[g],g,h):this._add(b,!1,h[g].tagName,h[g].readOnly))),g++;return a},is_traversed:function(){return la},is_good_tag:function(a){return jd("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[a.nodeName.toLowerCase()]?
!0:!1},is_html:function(a){return(a=z(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b=void 0;var c=a;var d={};Ma=0;for(b in c)ld.call(c,b)&&(d[b]=c[b],Ma++);return d},get_as_hash_node_dict:function(){var b=void 0;var c={};for(b in a){var d=a[b];K(a,b)&&(c[b]=d)}return c},get_as_pair_array:function(){var b=void 0;var c=[];for(b in a)ld.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var b,e,f;var h=[];if(!c){c=document.getElementsByTagName("body");if(!c.length)return{needed:!1,
selector:""};c=c[0]}a=a.concat(fd());var g=b=0;for(e=a.length;b<e;g=++b)a[g]=yc(a[g]);b=!1;e="";var k=0;for(f=a.length;k<f;k++)g=a[k],hd(c,g)&&h.push(g);h.length&&(b=!0,e=h.join(",").replace("class=","class^="));return{needed:b,selector:e}},length:function(){return Object.keys(a).length},reset:function(){a=[];return la=!1},add_child_nodes:function(a,c,d){var b,f;var g=a.node.childNodes;var l=0;for(f=g.length;l<f;l++)(b=g[l])&&b.nodeName&&!this._add(b,!1,a.tagName,a.readOnly)&&this.is_good_tag(b)&&
d.push({node:b,tagName:a.tagName,readOnly:a.readOnly,parent_id:c});return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f=null;"#text"===b.nodeName&&(f=z(b.nodeValue));c=c||!1;if("msie"===l.detect.browser&&9>l.detect.version&&e)return!1;if("msie"!==l.detect.browser||9<=l.detect.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(h){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){if(!a)return"";
var b=z(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,"");b=b+":"+a.substring(0,20);return b=gd(b)}}}();Fc=function(a,b,c){if(Y)return!1;var d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);var e=document.createElement("span");b=document.createDocumentFragment();e.innerHTML=d;if("msie"===l.detect.browser&&9>l.detect.version){d=a.previousSibling;var f=/^\s/;d&&d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" ");(d=a.nextSibling)&&
d.nodeValue&&d.nodeValue.length&&f.test(d.nodeValue[0])&&(d.nodeValue=" "+d.nodeValue)}for(;e.firstChild;)"#text"===e.firstChild.nodeName?(d=b.appendChild(e.firstChild),y.add_node(d)):(d=b.appendChild(e.firstChild),null===d||c||Db(d,!0));if(c=a.parentNode)return c.replaceChild(b,a)};var md=new L,nd=new L,df=function(){for(var a=[],b=new L,c=arguments.length,d=Array(c),e=0;e<c;e++)d[e]=arguments[e];d.forEach(function(c,d){if(!(c instanceof L))throw Error("Invalid ReadyState constructor arguments (index: "+
d+").");c.ready||(a.push(c),c.whenReady(function(){a=Ud(a,c);0===a.length&&b.setReady()}))});0===a.length&&b.setReady();return b}(md,nd),E={called:!1,pendingRequests:0,readyStates:{beaconApiResponse:md,postPageLoadBeaconHandler:nd,beacon:df}};x(function(a){var b=a.status;a=a.actions;a=void 0===a?[]:a;b&&"OK"===b&&q(a,function(a){var b=a.url;"pixel"===a.action&&Sa(b)})});var zc=0,Ac=x(function(a){lb(a,"BEACON_CALLBACK__PRE_PAGE_LOAD")}),Bc=x(function(a){lb(a,"BEACON_CALLBACK__POST_PAGE_LOAD")}),Cb=
x(function(a){lb(a,"BEACON_CALLBACK__AUX")}),u={campaign_ids:[],loading_started:(new Date).getTime(),linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},ef=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"\\s+")}}(),Gc=void 0,xb=void 0,od=void 0,yb=void 0;Gc=function(a){$a(a,"click",oa);ad||$a(a,"contextmenu",oa);return Db(a,!1)};od=function(a,b,c,d){var e=ef(a);var f="";
m.target&&(f='target="'+m.target+'"');b=ob(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a=Vb(ob(a));b='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+a+'"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6';c=e.replace(/\?:/g,"");return{search_regex:new RegExp(e,"i"),repl_regex:new RegExp(c,"i"),repl_text:b}};xb=function(a,b){var c,d,e=void 0,f;if(!a||Na(a,["span.skimlinks-unlinked"]))return[[],[]];var g=a.data;
var m=[];var k=[];for(d=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi;c=d.exec(g);){var n=c[0];if("link.phrase"!==n){var r=c.index;if(0<z(n).length&&-1===n.indexOf("/.")&&-1===n.indexOf("...")){var q=n;0!==n.indexOf("http")&&0!==n.indexOf("//")&&(q="msie"===l.detect.browser&&6>=l.detect.version?"http://"+n:"//"+n);c=xa(q);var t=rd({OriginalPhrase:""+n,Url:q,Title:"",ActionType:2,GroupId:0,Unlinked:!0});(f=od(""+n,q,Ha.creative,"skimlinks-unlinked"))&&k.push({start:r,
text:""+ob(n),domain:c,repl_regex:f.repl_regex,replacement:f.repl_text,regex:f.search_regex,phrase:t,link:q});m.push(c)}else break}}if(k.length){e=b;q="skimlinks-unlinked";var w;n=document.createDocumentFragment();var u=0;c=[];r=a.nodeValue;d=[];g=a.parentNode;q||(q="skimwords-potential");e||(e="-1");if(g){t=0;for(w=k.length;t<w;t++){var v=k[t];var x=document.createElement("span");x.className=q;f=document.createTextNode(r.substring(u,v.start));n.appendChild(f);x.innerHTML=v.text;n.appendChild(x);
u={};u.node=x;u.match=v;A(u,"occurrence",v.target_occurrence);c.push(u);u=v.start+v.text.length;d.push(f);y.add_node(f,e)}k=document.createTextNode(r.substring(u));d.push(k);n.appendChild(k);y.add_node(k,e);g.replaceChild(n,a)}e=[c,d];k=e[0];e=e[1];n=0;for(d=k.length;n<d;n++)g=k[n],Ha.url_spans.push(g)}e||(e=[]);return[m,e]};yb=function(a){var b;if(m.exclude.length){var c=m.exclude;var d=0;for(b=c.length;d<b;d++){var e=c[d];if(e===a)return!1}}if(m.include.length){c=m.include;d=0;for(b=c.length;d<
b;d++)if(e=c[d],e===a)return!0;return!1}return!0};var qb=!1,W=!1,ha=null,ia=null,He={detect:function(a){a:{try{var b=navigator.userAgent.toLowerCase();if(-1===b.indexOf("firefox")&&-1===b.indexOf("chrome")){W=!0;qb=!1;break a}}catch(c){}b=""+11*Math.random();ha=new Image;ha.onload=Pc;ha.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,b);ia=new Image;ia.onload=Pc;ia.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,b)}Oc(a,250)}},ja=x(function(){Rc(Bc);
document.removeEventListener("DOMContentLoaded",ja);document.removeEventListener("load",ja)}),Ge={skimlinks:!1,skimwords:!1,unlinked:!1,audience:!1,GDPRConsent:!1,incentivePopup:!1};Yb&&x(function(){t.on("skim_js_init",he);t.on("skim_js_init",me);t.on("EVENTS__BEACON_CALLBACK",pe,{isFirstCall:!0});we();t.on("skim_js_init",Ae);t.on("skim_js_start",Be);Fe()})()})();
